from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AD_Tool(object):
    def setupUi(self, AD_Tool):
        AD_Tool.setObjectName("AD_Tool")
        AD_Tool.resize(616, 700)
        self.layoutWidget = QtWidgets.QWidget(AD_Tool)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 21, 591, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_inputUsername = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_inputUsername.setText("")
        self.le_inputUsername.setObjectName("le_inputUsername")
        self.horizontalLayout.addWidget(self.le_inputUsername)
        self.bt_inquiry = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_inquiry.setObjectName("bt_inquiry")
        self.horizontalLayout.addWidget(self.bt_inquiry)
        self.le_inputPassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_inputPassword.setObjectName("le_inputPassword")
        self.horizontalLayout.addWidget(self.le_inputPassword)
        self.bt_resetPassword = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_resetPassword.setObjectName("bt_resetPassword")
        self.horizontalLayout.addWidget(self.bt_resetPassword)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.te_showDetails = QtWidgets.QTextEdit(self.layoutWidget)
        self.te_showDetails.setObjectName("te_showDetails")
        self.horizontalLayout_2.addWidget(self.te_showDetails)
        self.te_showCountdown = QtWidgets.QTextEdit(self.layoutWidget)
        self.te_showCountdown.setObjectName("te_showCountdown")
        self.horizontalLayout_2.addWidget(self.te_showCountdown)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(AD_Tool)
        QtCore.QMetaObject.connectSlotsByName(AD_Tool)

    def retranslateUi(self, AD_Tool):
        _translate = QtCore.QCoreApplication.translate
        AD_Tool.setWindowTitle(_translate("AD_Tool", "Dialog"))
        self.le_inputUsername.setPlaceholderText(_translate("AD_Tool", "请输入用户名"))
        self.bt_inquiry.setText(_translate("AD_Tool", "查询"))
        self.le_inputPassword.setPlaceholderText(_translate("AD_Tool", "请输入密码"))
        self.bt_resetPassword.setText(_translate("AD_Tool", "重置密码"))
